spring.application.name=AT

spring.datasource.url=jdbc:postgresql://ep-calm-resonance-atq7bxlo-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_0ibmxdQTfw5y
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always